name: Functional Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build MTK
        run: make build

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Create Database
        run: mysql -e 'CREATE DATABASE test_db;' -uroot -proot

      - name: Import Database
        run: mysql -uroot -proot test_db < .github/workflows/functional-test.sql

      - name: Dump Database
        run: bin/mtk-linux-amd64 dump test_db --port=3306 --user=root --password=root --host=127.0.0.1 > mtk-dump.sql

      - name: Drop Database
        run: mysql -e 'DROP DATABASE test_db;' -uroot -proot

      - name: Clean Database
        # Remove the last line from the file - the dump timestamp.
        run: sed '$d' mtk-dump.sql > mtk-dump-clean.sql

      - name: Recreate Database
        run: mysql -e 'CREATE DATABASE test_db;' -uroot -proot

      - name: Reimport Database
        run: mysql -uroot -proot test_db < mtk-dump-clean.sql

      - name: Compare Results
        run: diff -q .github/workflows/functional-test.sql mtk-dump-clean.sql
